const stufftoJson = [
    {
      adult: false,
      backdrop_path: '/mlolzwV6VrKOZJ1SfYbPHXXDD4p.jpg',
      genre_ids: [Array],
      id: 329,
      original_language: 'en',
      original_title: 'Jurassic Park',
      overview: 'A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA. Before opening day, he invites a team of experts and his two eager grandchildren to experience the park and help calm anxious investors. However, the park is anything but amusing as the security systems go off-line and the dinosaurs escape.',
      popularity: 29.017,
      poster_path: '/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg',
      release_date: '1993-06-11',
      title: 'Jurassic Park',
      video: false,
      vote_average: 7.9,
      vote_count: 14458
    },
    {
      adult: false,
      backdrop_path: '/xLjgy6mjefWzNzMKxfwfrKgoVTq.jpg',
      genre_ids: [Array],
      id: 788,
      original_language: 'en',
      original_title: 'Mrs. Doubtfire',
      overview: "Loving but irresponsible dad Daniel Hillard, estranged from his exasperated spouse, is crushed by a court order allowing only weekly visits with his kids. When Daniel learns his ex needs a housekeeper, he gets the job -- disguised as a British nanny. Soon he becomes not only his children's best pal but the kind of parent he should have been from the start.",
      popularity: 19.062,
      poster_path: '/szvidvi0Fo4j2gmMtk1sNe1rkzw.jpg',
      release_date: '1993-11-24',
      title: 'Mrs. Doubtfire',
      video: false,
      vote_average: 7.2,
      vote_count: 5400
    },
    {
      adult: false,
      backdrop_path: '/sdylVXKmMZb5nCRJiMUwfDzVDQJ.jpg',
      genre_ids: [Array],
      id: 5503,
      original_language: 'en',
      original_title: 'The Fugitive',
      overview: 'Wrongfully convicted of murdering his wife and sentenced to death, Richard Kimble escapes from the law in an attempt to find the real killer and clear his name.',
      popularity: 27.389,
      poster_path: '/b3rEtLKyOnF89mcK75GXDXdmOEf.jpg',
      release_date: '1993-08-06',
      title: 'The Fugitive',
      video: false,
      vote_average: 7.5,
      vote_count: 3621
    },
    {
      adult: false,
      backdrop_path: '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
      genre_ids: [Array],
      id: 424,
      original_language: 'en',
      original_title: "Schindler's List",
      overview: 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
      popularity: 56.298,
      poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
      release_date: '1993-12-15',
      title: "Schindler's List",
      video: false,
      vote_average: 8.6,
      vote_count: 13818
    },
    {
      adult: false,
      backdrop_path: '/rB4oTSg3PkH828b3hwn231brzwh.jpg',
      genre_ids: [Array],
      id: 37233,
      original_language: 'en',
      original_title: 'The Firm',
      overview: "Mitch McDeere is a young man with a promising future in Law. About to sit his Bar exam, he is approached by 'The Firm' and made an offer he doesn't refuse. Seduced by the money and gifts showered on him, he is totally oblivious to the more sinister side of his company. Then, two Associates are murdered. The FBI contact him, asking him for information and suddenly his life is ruined. He has a choice - work with the FBI, or stay with the Firm. Either way he will lose his life as he knows it. Mitch figures the only way out is to follow his own plan...",
      popularity: 17.979,
      poster_path: '/kFexXCzidkm4LwlgZqxsJsDQB5v.jpg',
      release_date: '1993-06-30',
      title: 'The Firm',
      video: false,
      vote_average: 6.7,
      vote_count: 1702
    },
    {
      adult: false,
      backdrop_path: '/qyeIkGJuxdjfimkB8eu9AzGZyGM.jpg',
      genre_ids: [Array],
      id: 4478,
      original_language: 'en',
      original_title: 'Indecent Proposal',
      overview: "John Gage offers a down-on-his-luck yuppie husband $1 million for the opportunity to spend the night with the man's wife.",
      popularity: 20.005,
      poster_path: '/a39WoiTJEG5kNLIrr3kOMwg3LFg.jpg',
      release_date: '1993-04-07',
      title: 'Indecent Proposal',
      video: false,
      vote_average: 6.3,
      vote_count: 1194
    },
    {
      adult: false,
      backdrop_path: '/yCOwgIIO0gYd7aEeyJ4oGM4h9Iy.jpg',
      genre_ids: [Array],
      id: 9350,
      original_language: 'en',
      original_title: 'Cliffhanger',
      overview: 'A year after losing his friend in a tragic 4,000-foot fall, former ranger Gabe Walker and his partner, Hal, are called to return to the same peak to rescue a group of stranded climbers, only to learn the climbers are actually thieving hijackers who are looking for boxes full of money.',
      popularity: 21.475,
      poster_path: '/8v2nPPLvhEVlfXu08UZ0djK31be.jpg',
      release_date: '1993-05-28',
      title: 'Cliffhanger',
      video: false,
      vote_average: 6.5,
      vote_count: 1995
    },
    {
      adult: false,
      backdrop_path: '/fROgQIALHJEmayqLITFHhOMW3ef.jpg',
      genre_ids: [Array],
      id: 858,
      original_language: 'en',
      original_title: 'Sleepless in Seattle',
      overview: "When Sam Baldwin's wife dies, he is left to bring up his eight-year-old son Jonah alone, and decides to move to Seattle to make a new start. On Christmas Eve, Jonah rings a radio phone-in with his Christmas wish to find a new wife for his dad. Meanwhile in Baltimore, journalist Annie Reed, who is having doubts about her own relationship, is listening in.",
      popularity: 16.727,
      poster_path: '/iLWsLVrfkFvOXOG9PbUAYg7AK3E.jpg',
      release_date: '1993-06-24',
      title: 'Sleepless in Seattle',
      video: false,
      vote_average: 6.7,
      vote_count: 1990
    },
    {
      adult: false,
      backdrop_path: '/qeuwxIkty0n302HVULQpJhwOMiu.jpg',
      genre_ids: [Array],
      id: 9800,
      original_language: 'en',
      original_title: 'Philadelphia',
      overview: 'Two competing lawyers join forces to sue a prestigious law firm for AIDS discrimination. As their unlikely friendship develops their courage overcomes the prejudice and corruption of their powerful adversaries.',
      popularity: 21.195,
      poster_path: '/tFe5Yoo5zT495okA49bq1vPPkiV.jpg',
      release_date: '1993-12-22',
      title: 'Philadelphia',
      video: false,
      vote_average: 7.7,
      vote_count: 3733
    },
    {
      adult: false,
      backdrop_path: '/dMFVSGbgtVTedpewA4PHykQuEEK.jpg',
      genre_ids: [Array],
      id: 9944,
      original_language: 'en',
      original_title: 'The Pelican Brief',
      overview: "A law student's theory about the recent deaths of two Supreme Court justices embroils her in a far-reaching web of murder, corruption, and greed.",
      popularity: 16.644,
      poster_path: '/1V9B0fk3dh2Af2yUI5mAEETJNNT.jpg',
      release_date: '1993-09-17',
      title: 'The Pelican Brief',
      video: false,
      vote_average: 6.6,
      vote_count: 1301
    },
    {
      adult: false,
      backdrop_path: '/poDeoxP4OSweHvOmrkVcaqZAOBk.jpg',
      genre_ids: [Array],
      id: 9386,
      original_language: 'en',
      original_title: 'In the Line of Fire',
      overview: 'Veteran Secret Service agent Frank Horrigan is a man haunted by his failure to save President Kennedy while serving protection detail in Dallas. Thirty years later, a man calling himself "Booth" threatens the life of the current President, forcing Horrigan to come back to protection detail to confront the ghosts from his past.',
      popularity: 15.89,
      poster_path: '/3NvOFpmyECI3DNExYMtFIRcGMsu.jpg',
      release_date: '1993-07-08',
      title: 'In the Line of Fire',
      video: false,
      vote_average: 7,
      vote_count: 1311
    },
    {
      adult: false,
      backdrop_path: '/2Y0lMMmfbpMbVMgc86oi8o5cFQX.jpg',
      genre_ids: [Array],
      id: 864,
      original_language: 'en',
      original_title: 'Cool Runnings',
      overview: 'When a Jamaican sprinter is disqualified from the Olympic Games, he enlists the help of a dishonored coach to start the first Jamaican bobsled team.',
      popularity: 15.333,
      poster_path: '/6O4N3PSitItDo1v3PMDiltOqTI9.jpg',
      release_date: '1993-10-01',
      title: 'Cool Runnings',
      video: false,
      vote_average: 7,
      vote_count: 1734
    },
    {
      adult: false,
      backdrop_path: '/mXkUfzJfdWx9y4Zlm7wsvQ0uvYo.jpg',
      genre_ids: [Array],
      id: 1634,
      original_language: 'en',
      original_title: 'Free Willy',
      overview: 'When maladjusted orphan Jesse vandalizes a theme park, he is placed with foster parents and must work at the park to make amends. There he meets Willy, a young Orca whale who has been separated from his family. Sensing kinship, they form a bond and, with the help of kindly whale trainer Rae Lindley, develop a routine of tricks. However, greedy park owner Dial soon catches wind of the duo and makes plans to profit from them.',
      popularity: 23.909,
      poster_path: '/1WLTjNznfvr3bkHf4p9PR4ctBKK.jpg',
      release_date: '1993-07-16',
      title: 'Free Willy',
      video: false,
      vote_average: 6.2,
      vote_count: 1586
    },
    {
      adult: false,
      backdrop_path: '/tGhWuZp1fdM0mftTWv88nxgkBUl.jpg',
      genre_ids: [Array],
      id: 1049,
      original_language: 'en',
      original_title: 'Sommersby',
      overview: 'Set in the South just after the US Civil War, Laurel Sommersby is just managing to work the farm without her husband, believed killed in battle. By all accounts, Jack Sommersby was not a pleasant man, thus when he suddenly returns, Laurel has mixed emotions. It appears that Jack has changed a great deal, leading some people to believe that this is not actually Jack but an imposter. Laurel herself is unsure, but willing to take the man into her home, and perhaps later into her heart.',
      popularity: 10.23,
      poster_path: '/tAgQKLv0GK97Tr0bvdI66oXlEVb.jpg',
      release_date: '1993-02-05',
      title: 'Sommersby',
      video: false,
      vote_average: 6.4,
      vote_count: 312
    },
    {
      adult: false,
      backdrop_path: '/bumIpNTKmLY380bruTgIDTrXfpZ.jpg',
      genre_ids: [Array],
      id: 9593,
      original_language: 'en',
      original_title: 'Last Action Hero',
      overview: 'Following the death of his father, young Danny Madigan takes comfort in watching action movies featuring the indestructible Los Angeles cop Jack Slater. After being given a magic ticket by theater manager Nick, Danny is sucked into the screen and bonds with Slater. When evil fictional villain Benedict gets his hands on the ticket and enters the real world, Danny and Jack must follow and stop him.',
      popularity: 22.602,
      poster_path: '/yTfjHPqh7C7bkfMtEKx2mPdorQw.jpg',
      release_date: '1993-06-18',
      title: 'Last Action Hero',
      video: false,
      vote_average: 6.4,
      vote_count: 2283
    },
    {
      adult: false,
      backdrop_path: '/3K54t5psPT0Ufqd2zbXK0sB4KUL.jpg',
      genre_ids: [Array],
      id: 9559,
      original_language: 'en',
      original_title: 'A Perfect World',
      overview: 'A kidnapped boy strikes up a friendship with his captor: an escaped convict on the run from the law, headed by an honorable U.S. Marshal.',
      popularity: 14.117,
      poster_path: '/1II9kMjOuho3pnEvxkpx7e3ozOO.jpg',
      release_date: '1993-11-24',
      title: 'A Perfect World',
      video: false,
      vote_average: 7.5,
      vote_count: 1392
    },
    {
      adult: false,
      backdrop_path: '/kBqxCAFpLmVxYQLwCKmmXVDtfyh.jpg',
      genre_ids: [Array],
      id: 9255,
      original_language: 'en',
      original_title: 'Hot Shots! Part Deux',
      overview: 'Topper Harley is found to be working as an odd-job-man in a monastery. The CIA want him to lead a rescue mission into Iraq, to rescue the last rescue team, who went in to rescue the last rescue team—who went in to rescue hostages left behind after Desert Storm.',
      popularity: 17.017,
      poster_path: '/zh9EGK970GHo10ETclWBOjZVUOK.jpg',
      release_date: '1993-05-21',
      title: 'Hot Shots! Part Deux',
      video: false,
      vote_average: 6.5,
      vote_count: 1591
    },
    {
      adult: false,
      backdrop_path: '/wN5EnpDUmrusp73qD0fZsOXtqVh.jpg',
      genre_ids: [Array],
      id: 10438,
      original_language: 'en',
      original_title: "Beethoven's 2nd",
      overview: "Beethoven is back -- and this time, he has a whole brood with him now that he's met his canine match, Missy, and fathered a family. The only problem is that Missy's owner, Regina, wants to sell the puppies and tear the clan apart. It's up to Beethoven and the Newton kids to save the day and keep everyone together.",
      popularity: 13.558,
      poster_path: '/biH5hW1BRfEr13oCizuAzpdBf2l.jpg',
      release_date: '1993-12-14',
      title: "Beethoven's 2nd",
      video: false,
      vote_average: 5.5,
      vote_count: 855
    },
    {
      adult: false,
      backdrop_path: '/nnCaXiYkrOSUh2Lo2P3N7ZjWpIp.jpg',
      genre_ids: [Array],
      id: 12139,
      original_language: 'en',
      original_title: 'Dennis the Menace',
      overview: "Mr. Wilson's ever-present annoyance comes in the form of one mischievous kid named Dennis. But he'll need Dennis's tricks to uncover a collection of gold coins that go missing when a shady drifter named Switchblade Sam comes to town.",
      popularity: 22.138,
      poster_path: '/Kl3HTDhJ1wNg9NpJwApE5mXGmo.jpg',
      release_date: '1993-06-23',
      title: 'Dennis the Menace',
      video: false,
      vote_average: 5.8,
      vote_count: 1278
    },
    {
      adult: false,
      backdrop_path: '/fwreQBx5CD55c1DpH117cS8915P.jpg',
      genre_ids: [Array],
      id: 867,
      original_language: 'en',
      original_title: 'Sliver',
      overview: "A woman moves into an apartment in Manhattan and learns that the previous tenant's life ended mysteriously after they fell from the balcony.",
      popularity: 23.009,
      poster_path: '/g7PC2e2KqDkIfOoJx9iXJJez99d.jpg',
      release_date: '1993-05-21',
      title: 'Sliver',
      video: false,
      vote_average: 5.4,
      vote_count: 558
    }
]

const jsonedStuff = []
  stufftoJson.forEach((element) => jsonedStuff.push(JSON.stringify(element)))

export default jsonedStuff
